package service

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/go-playground/validator/v10"
)

var validate = validator.New()

// validateConfig validates the structure of a Config
func validateConfig(cfg *Config) error {
	if err := validate.Struct(cfg); err != nil {
		return formatValidationError(err)
	}

	// Custom validations
	if err := validateTemplateVars(cfg.WorktreesDir); err != nil {
		return fmt.Errorf("invalid worktrees_dir template: %w", err)
	}

	return nil
}

// formatValidationError formats validation errors into readable messages
func formatValidationError(err error) error {
	if validationErrs, ok := err.(validator.ValidationErrors); ok {
		var messages []string
		for _, e := range validationErrs {
			// Map Go field names to YAML field names for better error messages
			yamlFieldName := structFieldToYAMLField(e.StructField())
			msg := fmt.Sprintf("field '%s': %s", yamlFieldName, translateValidationTag(e.Tag()))
			messages = append(messages, msg)
		}
		return fmt.Errorf("invalid config (.gbm/config.yaml):\n  - %s", strings.Join(messages, "\n  - "))
	}
	return err
}

// structFieldToYAMLField converts struct field names to YAML field names
func structFieldToYAMLField(fieldName string) string {
	// Map common struct fields to their YAML equivalents
	mapping := map[string]string{
		"DefaultBranch": "default_branch",
		"WorktreesDir":  "worktrees_dir",
		"Jira":          "jira",
		"FileCopy":      "file_copy",
	}
	if yaml, ok := mapping[fieldName]; ok {
		return yaml
	}
	return fieldName
}

// translateValidationTag converts validator tags to human-readable messages
func translateValidationTag(tag string) string {
	switch tag {
	case "required":
		return "required field is empty"
	case "url":
		return "must be valid URL"
	case "email":
		return "must be valid email address"
	case "min":
		return "value too short"
	case "max":
		return "value too long"
	default:
		return fmt.Sprintf("validation failed (%s)", tag)
	}
}

// validateTemplateVars validates that worktrees_dir only uses allowed template variables
func validateTemplateVars(path string) error {
	// Allowed template variables
	allowed := map[string]bool{
		"{gitroot}": true,
		"{branch}":  true,
		"{issue}":   true,
	}

	// Find all template variables in the path
	for i := 0; i < len(path); i++ {
		if path[i] == '{' {
			// Find closing brace
			j := i + 1
			for j < len(path) && path[j] != '}' {
				j++
			}
			if j >= len(path) {
				return fmt.Errorf("unclosed template variable in path: %s", path)
			}

			variable := path[i : j+1]
			if !allowed[variable] {
				return fmt.Errorf("invalid template variable '%s' (allowed: {gitroot}, {branch}, {issue})", variable)
			}

			i = j // Continue after closing brace
		}
	}

	return nil
}

// getDefaultBranch returns the default branch from git config, or "master" if not set
func getDefaultBranch() string {
	// Try git config init.defaultBranch first
	cmd := exec.Command("git", "config", "--get", "init.defaultBranch")
	if output, err := cmd.Output(); err == nil {
		branch := strings.TrimSpace(string(output))
		if branch != "" {
			return branch
		}
	}

	// Fall back to master
	return "master"
}

// generateExampleConfigYAML generates a well-commented example config
func generateExampleConfigYAML() string {
	defaultBranch := getDefaultBranch()

	return fmt.Sprintf(`# GBM Configuration
# Generated by: gbm init-config

# Default base branch for new branches (used with -b flag)
default_branch: %s

# Worktrees directory (relative to repo root)
# Supports templates: {gitroot}, {branch}, {issue}
worktrees_dir: worktrees

# Git remotes (optional)
# Configure remotes to set up in new repositories
#remotes:
#  origin:
#    url: git@github.com:user/repo.git
#  upstream:
#    url: git@github.com:org/repo.git

# JIRA integration (optional)
# Enables creating worktrees from JIRA issues
#jira:
#  enabled: true
#  host: https://jira.company.com
#  username: user@company.com
#  api_token: ${JIRA_API_TOKEN}  # Or paste token directly
#  jql: "assignee = currentUser() AND status != Done"
#  branch_prefix: feature/

# File copying (optional)
# Automatically copy files when creating worktrees
#file_copy:
#  # Rule-based copying
#  rules:
#    - source_worktree: main
#      files:
#        - ".env"
#        - "config/"
#
#  # Automatic copying
#  auto:
#    enabled: false
#    source_worktree: "{default}"  # {default}, {current}, or worktree name
#    copy_ignored: true            # Copy .gitignored files
#    copy_untracked: false         # Copy untracked files
#    exclude:                      # Exclude patterns (gitignore syntax)
#      - "*.log"
#      - "node_modules/"
#      - ".DS_Store"
`, defaultBranch)
}

// GenerateExampleConfig creates a .gbm/config.yaml file with example configuration
func GenerateExampleConfig(path string) error {
	// Check if config already exists
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("config already exists at %s (use --force to overwrite)", path)
	}

	// Create directory
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	// Generate config with detected default branch
	configYAML := generateExampleConfigYAML()

	// Write example config
	if err := os.WriteFile(path, []byte(configYAML), 0o644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}
