package service

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestGenerateExampleConfig_Creates(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".gbm", "config.yaml")

	err := GenerateExampleConfig(configPath)
	require.NoError(t, err)

	// Verify file exists
	assert.FileExists(t, configPath)

	// Verify content
	data, err := os.ReadFile(configPath)
	require.NoError(t, err)
	content := string(data)

	// Should contain key sections
	assert.Contains(t, content, "default_branch:")
	assert.Contains(t, content, "worktrees_dir:")
	assert.Contains(t, content, "# JIRA integration")
	assert.Contains(t, content, "# File copying")
}

func TestGenerateExampleConfig_ValidYAML(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, ".gbm", "config.yaml")

	err := GenerateExampleConfig(configPath)
	require.NoError(t, err)

	// Verify content is valid YAML
	data, err := os.ReadFile(configPath)
	require.NoError(t, err)

	var cfg Config
	err = yaml.Unmarshal(data, &cfg)
	require.NoError(t, err)

	// Verify basic structure
	assert.NotEmpty(t, cfg.DefaultBranch)
	assert.Equal(t, "worktrees", cfg.WorktreesDir)
}

func TestGenerateExampleConfig_AlreadyExists(t *testing.T) {
	tmpDir := t.TempDir()
	gbmDir := filepath.Join(tmpDir, ".gbm")
	err := os.MkdirAll(gbmDir, 0755)
	require.NoError(t, err)

	configPath := filepath.Join(gbmDir, "config.yaml")
	err = os.WriteFile(configPath, []byte("existing"), 0644)
	require.NoError(t, err)

	// Try to generate (should fail)
	err = GenerateExampleConfig(configPath)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "already exists")

	// Verify original content unchanged
	data, err := os.ReadFile(configPath)
	require.NoError(t, err)
	assert.Equal(t, "existing", string(data))
}

func TestGenerateExampleConfig_CreatesDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "a", "b", "c", ".gbm", "config.yaml")

	err := GenerateExampleConfig(configPath)
	require.NoError(t, err)

	assert.FileExists(t, configPath)
}

func TestGetDefaultBranch_ReturnsValue(t *testing.T) {
	// This test just validates the function returns a non-empty string
	// The actual value depends on git config which varies per environment
	branch := getDefaultBranch()
	assert.NotEmpty(t, branch)
}

func TestGenerateExampleConfigYAML_ContainsComments(t *testing.T) {
	content := generateExampleConfigYAML()

	// Verify it contains documentation
	assert.Contains(t, content, "# GBM Configuration")
	assert.Contains(t, content, "# Generated by: gbm init-config")
	assert.Contains(t, content, "# Default base branch")
	assert.Contains(t, content, "# Worktrees directory")
	assert.Contains(t, content, "# Git remotes")
	assert.Contains(t, content, "# JIRA integration")
	assert.Contains(t, content, "# File copying")
}

func TestGenerateExampleConfigYAML_ContainsDefaultBranch(t *testing.T) {
	content := generateExampleConfigYAML()

	// Should have default_branch set to git config value or fallback
	assert.Contains(t, content, "default_branch:")
	// Parse to make sure it's valid YAML
	var cfg Config
	err := yaml.Unmarshal([]byte(content), &cfg)
	require.NoError(t, err)
	assert.NotEmpty(t, cfg.DefaultBranch)
}

func TestGenerateExampleConfigYAML_HasValidExample(t *testing.T) {
	content := generateExampleConfigYAML()
	var cfg Config
	err := yaml.Unmarshal([]byte(content), &cfg)
	require.NoError(t, err)

	// Core fields must be set
	assert.NotEmpty(t, cfg.DefaultBranch)
	assert.Equal(t, "worktrees", cfg.WorktreesDir)
}
