package service

import (
	"fmt"
	"gbm/internal/jira"
	"strings"
	"time"
)

// extractAcceptanceCriteria searches for "Acceptance Criteria" heading in parsed description
// and extracts content until the next heading. Returns empty string if not found.
func extractAcceptanceCriteria(description string) string {
	if description == "" {
		return ""
	}

	lines := strings.Split(description, "\n")
	var inAC bool
	var ac strings.Builder

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Check if we've found the Acceptance Criteria heading
		if !inAC && strings.Contains(strings.ToLower(trimmed), "acceptance criteria") {
			inAC = true
			continue
		}

		// If we're in the AC section
		if inAC {
			// Stop at next heading (lines starting with #)
			if strings.HasPrefix(trimmed, "#") {
				break
			}
			// Append line to AC
			ac.WriteString(line + "\n")
		}
	}

	result := strings.TrimSpace(ac.String())
	if result == "" {
		return ""
	}

	return result
}

// generateJiraMarkdown generates markdown file content from JIRA ticket details.
func generateJiraMarkdown(ticket *jira.JiraTicketDetails) string {
	var md strings.Builder

	// Header with key and summary
	md.WriteString(fmt.Sprintf("# %s: %s\n\n", ticket.Key, ticket.Summary))

	// Metadata section (two trailing spaces for Markdown line breaks)
	md.WriteString(fmt.Sprintf("**URL**: %s  \n", ticket.URL))
	md.WriteString(fmt.Sprintf("**Status**: %s  \n", ticket.Status))
	if ticket.Priority != "" {
		md.WriteString(fmt.Sprintf("**Priority**: %s  \n", ticket.Priority))
	}
	if ticket.Assignee != "" {
		md.WriteString(fmt.Sprintf("**Assignee**: %s  \n", ticket.Assignee))
	}
	if !ticket.Created.IsZero() {
		md.WriteString(fmt.Sprintf("**Created**: %s  \n", ticket.Created.Format("2006-01-02")))
	}
	if ticket.DueDate != nil && !ticket.DueDate.IsZero() {
		md.WriteString(fmt.Sprintf("**Due Date**: %s  \n", ticket.DueDate.Format("2006-01-02")))
	}
	if ticket.Epic != "" {
		md.WriteString(fmt.Sprintf("**Epic**: %s  \n", ticket.Epic))
	}
	md.WriteString("\n")

	// Summary section
	md.WriteString("## Summary\n\n")
	md.WriteString(ticket.Summary + "\n\n")

	// Description section
	if ticket.Description != "" {
		md.WriteString("## Description\n\n")
		md.WriteString(ticket.Description + "\n\n")
	}

	// Acceptance Criteria section
	md.WriteString("## Acceptance Criteria\n\n")
	ac := extractAcceptanceCriteria(ticket.Description)
	if ac != "" {
		md.WriteString(ac + "\n\n")
	} else {
		md.WriteString("*Please extract from description above*\n\n")
	}

	// Parent section (after issue details, before Children section)
	if ticket.Parent != nil {
		md.WriteString("## Parent\n\n")
		md.WriteString(fmt.Sprintf("- **Parent:** %s - %s\n\n", ticket.Parent.Key, ticket.Parent.Summary))
	}

	// Children section (after Parent section, before Linked Issues)
	if len(ticket.Children) > 0 {
		md.WriteString("## Children\n\n")
		for _, child := range ticket.Children {
			md.WriteString(fmt.Sprintf("- **is parent of:** %s - %s\n", child.Key, child.Summary))
		}
		md.WriteString("\n")
	}

	// Footer with generation timestamp
	md.WriteString("---\n")
	md.WriteString(fmt.Sprintf("*Generated by gbm on %s*\n", time.Now().Format("2006-01-02 15:04:05")))

	return md.String()
}
